# Base Image
FROM node:20

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./

COPY src ./src


RUN npm i

ENV PORT=4000
ENV DBURL=mongodb+srv://siddhesh:sidd%40123@cluster0.dulnyi9.mongodb.net/ECOMMERCE?retryWrites=true&w=majority&appName=Cluster0
ENV JWT_SECRET=12354fgdtqwwer5ed
ENV JWT_EXPIRES=5d 


EXPOSE 4000

CMD [ "npm", "run", "dev" ]
