version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: siddhesh
      MONGO_INITDB_ROOT_PASSWORD: sidd1212

  my-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DBURL: "mongodb://siddhesh:sidd1212@mongodb"
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: siddhesh
      ME_CONFIG_MONGODB_ADMINPASSWORD: sidd1212
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
